#os: test
#os: Visual Studio 2015 RC

cache:
#  - packages -> **\packages.config
  - packages

before_build:
  - ps: nuget restore "$env:appveyor_build_folder\Xunit20Tests.sln"
#  - nuget install xunit.runners -prerelease -excludeversion
#  - set xunit20=%APPVEYOR_BUILD_FOLDER%\xunit.runners\tools

before_test:
  - dir C:\projects\xunit-20-tests\Xunit20Tests_AnyCPU\bin\Debug\

notifications:
  - provider: Webhook
    url: http://requestb.in/zx6wurzx
    on_build_success: true
    on_build_failure: true

#test:
#  assemblies:
#  - Xunit20Tests_AnyCPU.dll
